# Generated by Django 4.0.6 on 2022-07-22 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_name'),
        ('customers', '0002_alter_customer_options_alter_customer_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='Дата продажи')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
            ],
            options={
                'verbose_name': 'Реестр',
                'verbose_name_plural': 'Реестр',
                'ordering': ['sale_date', 'customer'],
            },
        ),
        migrations.CreateModel(
            name='RegistryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Кол-во')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='Сумма')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrys.registry')),
            ],
            options={
                'verbose_name': 'Реестр',
                'verbose_name_plural': 'Реестр',
                'ordering': ['-registry', 'sum'],
            },
        ),
    ]
