# Generated by Django 4.0.6 on 2022-07-22 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name'),
        ('customers', '0002_alter_customer_options_alter_customer_photo'),
        ('registrys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='registrydata',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='registrydata',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='registrydata',
            name='registry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrys.registry', verbose_name='Строка реестра'),
        ),
        migrations.AlterField(
            model_name='registrydata',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='Сумма'),
        ),
    ]
