# Generated by Django 4.0.6 on 2022-07-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена покупки')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена продажи')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
