# Generated by Django 4.0.6 on 2022-07-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=200, verbose_name='ФИО')),
                ('birthDate', models.DateField(verbose_name='Дата рождения')),
                ('registerDate', models.DateField(auto_now=True, verbose_name='Дата регистрации')),
                ('gender', models.CharField(choices=[('', ''), ('m', 'мужской'), ('w', 'женский')], default=None, max_length=1, verbose_name='Пол')),
                ('PDConsent', models.BooleanField(default=False, verbose_name='Согласие на обработку ПД')),
                ('photo', models.ImageField(upload_to='CustomersPhotos', verbose_name='Фотография')),
            ],
            options={
                'ordering': ['FIO', 'birthDate', 'registerDate'],
            },
        ),
    ]
