# Generated by Django 4.0.6 on 2022-07-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['FIO', 'birthDate', 'registerDate'], 'verbose_name': 'Покупатель (я)', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='CustomersPhotos/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
